development:
  adapter: postgresql
  encoding: utf8
  database: some_blog_dev
  username: postgres
  password: <%= ENV["POSTGRES_PASS"] %>
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: some_blog_test
  username: postgres
  password: <%= ENV["POSTGRES_PASS"] %>
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: utf8
  database: some_blog
  username: postgres
  password: <%= ENV["POSTGRES_PASS"] %>
  host: localhost
  port: 5432
